services:
  postgres:
    image: postgres:15

    environment:
      POSTGRES_DB: ${POSTGRES_DB:?Defina POSTGRES_DB no .env}
      POSTGRES_USER: ${POSTGRES_USER:?Defina POSTGRES_USER no .env}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?Defina POSTGRES_PASSWORD no .env}

    ports:
      - "127.0.0.1:${POSTGRES_PORT:-5434}:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U \"$${POSTGRES_USER}\" -d \"$${POSTGRES_DB}\""]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  wildfly:
    build:
      context: .
      dockerfile: Dockerfile

    image: conquistas-wildfly:dev

    environment:
      DB_URL: ${DB_URL:?Defina DB_URL no .env}
      DB_USER: ${POSTGRES_USER:?Defina POSTGRES_USER no .env}
      DB_PASSWORD: ${POSTGRES_PASSWORD:?Defina POSTGRES_PASSWORD no .env}


    ports:
      - "127.0.0.1:${WILDFLY_HTTP_PORT:-8080}:8080"

    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data: